/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uchicago_cs_encsel_query_offheap_EqualJniScalar */

#ifndef _Included_edu_uchicago_cs_encsel_query_offheap_EqualJniScalar
#define _Included_edu_uchicago_cs_encsel_query_offheap_EqualJniScalar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uchicago_cs_encsel_query_offheap_EqualJniScalar
 * Method:    executeDirect
 * Signature: (Ljava/nio/ByteBuffer;IIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_uchicago_cs_encsel_query_offheap_EqualJniScalar_executeDirect
  (JNIEnv *, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     edu_uchicago_cs_encsel_query_offheap_EqualJniScalar
 * Method:    executeHeap
 * Signature: ([BIIII)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_uchicago_cs_encsel_query_offheap_EqualJniScalar_executeHeap
  (JNIEnv *, jobject, jbyteArray, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
